name: Run GQA Visualization

on: [push, pull_request]

jobs:
  run-gqa-vis:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run GQA_vis.sh script
        run: |
          chmod +x GQA_vis.sh
          ./GQA_vis.sh

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: out/
